name: Run Compose Test

on:
  pull_request:

jobs:
  compose-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run docker compose test
        run: docker compose -f "compose.test.yaml" up --build --abort-on-container-exit
      - name: Tear down docker compose
        if: always()
        run: docker compose -f "compose.test.yaml" down
